name: Build and Release

on:
  release:
    types: [created]

# Add explicit permissions needed for release asset uploads
permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build and Upload
    
    # Use release tag for reference
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and package for macOS/Linux
        if: matrix.platform != 'win'
        shell: bash
        run: |
          # For macOS on GitHub Actions, we'll detect the architecture
          if [[ "${{ matrix.platform }}" == "mac" ]]; then
            arch=$(uname -m)
            echo "Building for macOS on $arch architecture"
            npm run make
            # Give a moment for file handles to close properly
            sleep 3
          else
            echo "Building for Linux"
            npm run make
            # Give a moment for file handles to close properly
            sleep 3
          fi
      
      - name: Build and package for Windows
        if: matrix.platform == 'win'
        shell: pwsh
        run: |
          Write-Host "Building for Windows"
          npm run make
          # Give a moment for file handles to close properly
          Start-Sleep -Seconds 3
      
      - name: Determine macOS architecture
        if: matrix.platform == 'mac'
        id: mac-arch
        run: |
          arch=$(uname -m)
          if [ "$arch" = "x86_64" ]; then
            echo "arch=x64" >> $GITHUB_OUTPUT
            echo "filename_arch=x64" >> $GITHUB_OUTPUT
          elif [ "$arch" = "arm64" ]; then
            echo "arch=arm64" >> $GITHUB_OUTPUT
            echo "filename_arch=arm64" >> $GITHUB_OUTPUT
          else
            echo "Unknown architecture: $arch"
            exit 1
          fi

      - name: Get version from package.json (Unix)
        if: matrix.platform != 'win'
        id: get-version-unix
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"
          
      - name: Get version from package.json (Windows)
        if: matrix.platform == 'win'
        id: get-version-win
        shell: powershell
        run: |
          $VERSION = (node -p "require('./package.json').version")
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Check for macOS archive
        if: matrix.platform == 'mac'
        id: check-mac-archive
        run: |
          arch="${{ steps.mac-arch.outputs.arch }}"
          VERSION="${{ steps.get-version-unix.outputs.version }}"
          echo "Checking for macOS $arch archive with version $VERSION"
          find ./out -type f -name "*.zip" | sort
          if [ -f "./out/make/zip/darwin/$arch/bfg-repo-cleaner-gui-darwin-$arch-$VERSION.zip" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Archive found: ./out/make/zip/darwin/$arch/bfg-repo-cleaner-gui-darwin-$arch-$VERSION.zip"
            # Ensure file is not locked by any process
            sleep 2
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Archive not found for $arch"
            find ./out/make -type f
          fi

      - name: Upload macOS artifacts
        if: matrix.platform == 'mac' && steps.check-mac-archive.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/zip/darwin/${{ steps.mac-arch.outputs.arch }}/bfg-repo-cleaner-gui-darwin-${{ steps.mac-arch.outputs.arch }}-${{ steps.get-version-unix.outputs.version }}.zip
          asset_name: bfg-repo-cleaner-gui-darwin-${{ steps.mac-arch.outputs.arch }}-${{ steps.get-version-unix.outputs.version }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for Windows artifacts
        if: matrix.platform == 'win'
        id: check-win-artifact
        shell: powershell
        run: |
          # Use the version from the previous step
          $VERSION = "${{ steps.get-version-win.outputs.version }}"
          Write-Host "Package version: $VERSION"
          
          Write-Host "Checking for Windows installer"
          $installerPath = "./out/make/squirrel.windows/x64/bfg-repo-cleaner-gui-$VERSION Setup.exe"
          
          # Try to find the installer file if it's not in the expected location
          if (-not (Test-Path -Path $installerPath)) {
            Write-Host "Installer not found at expected path, searching for it..."
            $foundFiles = Get-ChildItem -Path "./out" -Recurse -File -Filter "*Setup.exe" | Select-Object -First 1
            
            if ($foundFiles) {
              $installerPath = $foundFiles.FullName
              Write-Host "Found installer at: $installerPath"
            } else {
              Write-Host "No installer files found"
              Get-ChildItem -Path "./out" -Recurse -File | ForEach-Object { $_.FullName }
            }
          }
          
          if (Test-Path -Path $installerPath) {
            echo "exists=true" >> $env:GITHUB_OUTPUT
            echo "setup_path=$installerPath" >> $env:GITHUB_OUTPUT
            Write-Host "Installer found at: $installerPath"
          } else {
            echo "exists=false" >> $env:GITHUB_OUTPUT
            Write-Host "Installer not found"
          }

      - name: Upload Windows artifacts
        if: matrix.platform == 'win' && steps.check-win-artifact.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.check-win-artifact.outputs.setup_path }}
          asset_name: bfg-repo-cleaner-gui-${{ steps.get-version-win.outputs.version }}-Setup.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for Linux Deb artifacts
        if: matrix.platform == 'linux'
        id: check-linux-deb
        run: |
          VERSION="${{ steps.get-version-unix.outputs.version }}"
          echo "Checking for Linux deb package with version $VERSION"
          if test -f "./out/make/deb/x64/bfg-repo-cleaner-gui_${VERSION}_amd64.deb"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Deb package found"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Deb package not found"
            find ./out/make -type f
          fi

      - name: Upload Linux Deb artifacts
        if: matrix.platform == 'linux' && steps.check-linux-deb.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/deb/x64/bfg-repo-cleaner-gui_${{ steps.get-version-unix.outputs.version }}_amd64.deb
          asset_name: bfg-repo-cleaner-gui_${{ steps.get-version-unix.outputs.version }}_amd64.deb
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for Linux RPM artifacts
        if: matrix.platform == 'linux'
        id: check-linux-rpm
        run: |
          VERSION="${{ steps.get-version-unix.outputs.version }}"
          echo "Checking for Linux rpm package with version $VERSION"
          if test -f "./out/make/rpm/x64/bfg-repo-cleaner-gui-${VERSION}-1.x86_64.rpm"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "RPM package found"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "RPM package not found"
            find ./out/make -type f
          fi

      - name: Upload Linux RPM artifacts
        if: matrix.platform == 'linux' && steps.check-linux-rpm.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/rpm/x64/bfg-repo-cleaner-gui-${{ steps.get-version-unix.outputs.version }}-1.x86_64.rpm
          asset_name: bfg-repo-cleaner-gui-${{ steps.get-version-unix.outputs.version }}-1.x86_64.rpm
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate and upload electron-updater metadata files
      - name: Generate update metadata files
        if: always() # Run even if some builds fail
        run: |
          npm run generate-update-files

      - name: Upload latest-mac.yml
        if: matrix.platform == 'mac' && steps.check-mac-archive.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./update-files/latest-mac.yml
          asset_name: latest-mac.yml
          asset_content_type: application/x-yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload latest-linux.yml
        if: matrix.platform == 'linux' && (steps.check-linux-deb.outputs.exists == 'true' || steps.check-linux-rpm.outputs.exists == 'true')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./update-files/latest-linux.yml
          asset_name: latest-linux.yml
          asset_content_type: application/x-yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # In case Linux metadata file doesn't exist

      - name: Generate Windows metadata and upload
        if: matrix.platform == 'win' && steps.check-win-artifact.outputs.exists == 'true'
        shell: powershell
        run: |
          # Create latest.yml for Windows (Squirrel.Windows format)
          $VERSION = "${{ steps.get-version-win.outputs.version }}"
          $SETUP_FILE = "bfg-repo-cleaner-gui-$VERSION-Setup.exe"
          
          # Calculate file hash
          $fileHash = Get-FileHash -Path "${{ steps.check-win-artifact.outputs.setup_path }}" -Algorithm SHA512
          $sha512 = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($fileHash.Hash.ToLower()))
          
          # Get file size
          $fileSize = (Get-Item "${{ steps.check-win-artifact.outputs.setup_path }}").Length
          
          # Create metadata content
          $metadataContent = @"
          version: $VERSION
          files:
            - url: $SETUP_FILE
              sha512: $sha512
              size: $fileSize
          path: $SETUP_FILE
          sha512: $sha512
          releaseDate: '$((Get-Date).ToString("yyyy-MM-ddTHH:mm:ss.fffZ"))'
          "@
          
          # Ensure update-files directory exists
          if (-not (Test-Path -Path "./update-files")) {
            New-Item -ItemType Directory -Path "./update-files" -Force
          }
          
          # Write metadata file
          $metadataContent | Out-File -FilePath "./update-files/latest.yml" -Encoding UTF8
          Write-Host "Generated latest.yml for Windows"

      - name: Upload latest.yml (Windows)
        if: matrix.platform == 'win' && steps.check-win-artifact.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./update-files/latest.yml
          asset_name: latest.yml
          asset_content_type: application/x-yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
