name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and package
        run: npm run make
      
      - name: Upload macOS artifacts
        if: matrix.platform == 'mac'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/zip/darwin/x64/bfg-repo-cleaner-gui-darwin-x64-1.0.0.zip
          asset_name: bfg-repo-cleaner-gui-mac-x64.zip
          asset_content_type: application/zip

      - name: Upload macOS arm64 artifacts
        if: matrix.platform == 'mac'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/zip/darwin/arm64/bfg-repo-cleaner-gui-darwin-arm64-1.0.0.zip
          asset_name: bfg-repo-cleaner-gui-mac-arm64.zip
          asset_content_type: application/zip
      
      - name: Upload Windows artifacts
        if: matrix.platform == 'win'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/squirrel.windows/x64/bfg-repo-cleaner-gui-1.0.0 Setup.exe
          asset_name: bfg-repo-cleaner-gui-windows-setup.exe
          asset_content_type: application/octet-stream
      
      - name: Upload Linux Deb artifacts
        if: matrix.platform == 'linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/deb/x64/bfg-repo-cleaner-gui_1.0.0_amd64.deb
          asset_name: bfg-repo-cleaner-gui-linux-amd64.deb
          asset_content_type: application/octet-stream
      
      - name: Upload Linux RPM artifacts
        if: matrix.platform == 'linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/make/rpm/x64/bfg-repo-cleaner-gui-1.0.0-1.x86_64.rpm
          asset_name: bfg-repo-cleaner-gui-linux-x86_64.rpm
          asset_content_type: application/octet-stream
